name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Verify checked out branch
        run: |
          echo "Current ref: $GITHUB_REF"
          git branch
          ls -la

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Zecyel
          password: ${{ secrets.GHCR_PAT }}  # 使用自定义的 PAT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/danshi-dev/danshi:latest