name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Verify checked out branch
        run: |
          echo "Current ref: $GITHUB_REF"
          git branch
          ls -la

      - name: Create env_file file from Secrets
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> env_file
          echo "MONGO_DB=${{ secrets.MONGO_DB }}" >> env_file
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> env_file
          echo "TEST_ENV_VARIANT=${{ secrets.TEST_ENV_VARIANT }}" >> env_file

      - name: Inject env_file into Code
        run: python3 injector.py

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Zecyel
          password: ${{ secrets.GHCR_PAT }} # 使用自定义的 PAT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/danshi-dev/danshi:latest
